[build]
command = "pipenv install; pipenv run statik"
publish = "public"

[[redirects]]
from = "/slack"
to = "https://join.slack.com/t/pythonadelaide/shared_invite/enQtMjk2NDM1ODAxNDc1LWY0ODYxNjgzOTJhZTRmM2FiY2ZkODQ0MjVhNTkwMGQwOWQ3NjE3OWYwM2I3MTNmMDVkODdiZDRhNjA5MGM2MWU"

[[redirects]]
from = "/feedback"
to = "https://adambrenecki.typeform.com/to/clwIU1"
