[build]
command = "pipenv install; pipenv run statik"
publish = "public"

[[redirects]]
from = "/slack"
to = "https://join.slack.com/t/pythonadelaide/shared_invite/zt-dfwcdxxu-NOEpVNuqLL1yipcbcHqMHQ"

[[redirects]]
from = "/feedback"
to = "https://adambrenecki.typeform.com/to/clwIU1"
